name: Build Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Publish Sarah
    uses: GroupeZ-dev/actions/.github/workflows/build.yml@main
    with:
      project-name: "Sarah"
      publish: true
      publish-on-discord: false
      project-to-publish: "API:publish"
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
